# Generated by Django 4.2.4 on 2023-10-02 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Login', 'Login'), ('Register', 'Register'), ('Logout', 'Logout')], max_length=20)),
                ('client_ip', models.GenericIPAddressField(verbose_name='IP')),
                ('device', models.CharField(max_length=40, verbose_name='دستگاه')),
                ('os', models.CharField(max_length=40, verbose_name='سیستم عامل')),
                ('os_version', models.CharField(max_length=20, verbose_name='نسخه سیستم عامل')),
                ('browser', models.CharField(max_length=40, verbose_name='مرورگر')),
                ('browser_version', models.CharField(max_length=20, verbose_name='نسخه مرورگر')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authentication_log', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
