# Generated by Django 4.2.4 on 2023-11-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticationlog',
            options={'ordering': ('-created',), 'verbose_name': 'لاگ', 'verbose_name_plural': 'لاگ ها'},
        ),
        migrations.AlterField(
            model_name='authenticationlog',
            name='type',
            field=models.CharField(choices=[('Login', 'Login'), ('Register', 'Register'), ('Logout', 'Logout')], max_length=20, verbose_name='نوع'),
        ),
    ]
