# Generated by Django 4.2.4 on 2023-08-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=35, unique=True)),
                ('slug', models.SlugField(max_length=30, primary_key=True, serialize=False, verbose_name='Display Name')),
                ('sidebar', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-sidebar'],
            },
        ),
    ]
