# Generated by Django 4.2.4 on 2023-08-25 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=30, primary_key=True, serialize=False, verbose_name='url')),
                ('main_image', models.ImageField(upload_to='articles_images/', verbose_name='تصویر اصلی')),
                ('body', models.TextField(verbose_name='متن مقاله')),
                ('views', models.IntegerField(default=0, verbose_name='تعداد بازدید ها')),
                ('banner', models.BooleanField(default=False, help_text='نشان دادن درون بنر اصلی سایت درون صغحه خانه', verbose_name='Home Banner')),
                ('home_item', models.BooleanField(default=False, help_text='قرار گرفتن در مقاله های خانه')),
                ('published', models.BooleanField(default=False, help_text='تا وقتی دکمه انتشار تیک نخورد این مقاله در هیچ کدام از صفحات وبسایت قابل رؤیت نخواهد بود', verbose_name='انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['published', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=35, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=30, primary_key=True, serialize=False, verbose_name='url')),
                ('sidebar', models.BooleanField(default=False, help_text='نشان دادن در سایدبار')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['-sidebar'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300, verbose_name='متن کامنت')),
                ('published', models.BooleanField(default=False, help_text='تا وقتی دکمه انتشار تیک نخورد این کامنت در هیچ کدام از صفحات وبسایت قابل رؤیت نخواهد بود', verbose_name='انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.article', verbose_name='مقاله')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='article.comment', verbose_name='ریپلای')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(verbose_name='IP')),
                ('device', models.CharField(max_length=40, verbose_name='دستگاه')),
                ('os', models.CharField(max_length=40, verbose_name='سیستم عامل')),
                ('os_version', models.CharField(max_length=20, verbose_name='نسخه سیستم عامل')),
                ('browser', models.CharField(max_length=40, verbose_name='مرورگر')),
                ('browser_version', models.CharField(max_length=20, verbose_name='نسخه مرورگر')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='article.article', verbose_name='مقاله')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_requests', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'بازدید مقاله',
                'verbose_name_plural': 'بازدید های مقالات',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='article.category', verbose_name='دسته بندی های مقاله'),
        ),
    ]
