# Generated by Django 4.2.4 on 2023-08-09 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sidebar',
            field=models.BooleanField(default=False, help_text='show in sidebar'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=30, primary_key=True, serialize=False, verbose_name='Display Name')),
                ('body', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('banner', models.BooleanField(default=False, help_text='show in home banners', verbose_name='Home Banner')),
                ('home_item', models.BooleanField(default=False, help_text='show in home page articles')),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='article.category')),
            ],
        ),
    ]
