# Generated by Django 4.2.4 on 2023-08-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_category_sidebar_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ImageField(default='', upload_to='article_images/<django.db.models.fields.CharField>'),
            preserve_default=False,
        ),
    ]
