# Generated by Django 4.2.4 on 2023-08-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(upload_to='articles_images/'),
        ),
    ]
