# Generated by Django 4.2.4 on 2023-08-25 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField(max_length=150, verbose_name='متن کوتاه سایدبار')),
                ('website_title', models.CharField(max_length=35)),
                ('website_logo', models.ImageField(upload_to='main_images', verbose_name='لوگو 1')),
                ('phone', models.IntegerField(verbose_name='شماره موبایل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('country', models.CharField(max_length=20, verbose_name='کشکور')),
                ('city', models.CharField(max_length=20, verbose_name='شهر')),
                ('about_text', models.TextField(verbose_name='متن صفحه درباره ما')),
                ('main_logo', models.ImageField(upload_to='main_images', verbose_name='لوگو اصلی')),
                ('about_image', models.ImageField(upload_to='main_images', verbose_name='تصویر صفحه درباره ما')),
            ],
            options={
                'verbose_name': 'اطلاعات اصلی',
                'verbose_name_plural': 'اطلاعات اصلی',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(default='https://facebook.com')),
                ('twitter', models.URLField(default='https://twitter.com')),
                ('instagram', models.URLField(default='https://www.instagram.com/')),
                ('pinterest', models.URLField(default='https://www.pinterest.com/')),
                ('youtube', models.URLField(default='https://youtube.com/')),
            ],
            options={
                'verbose_name': 'شبکه های اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('title', models.CharField(max_length=150, verbose_name='موضوع')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False, verbose_name='خوانده شده ؟')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پیام کاربر',
                'verbose_name_plural': 'پیام های کاربران',
                'ordering': ['read', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=40, verbose_name='صفحه بازدید شده')),
                ('client_ip', models.GenericIPAddressField(verbose_name='IP')),
                ('device', models.CharField(max_length=40, verbose_name='دستگاه')),
                ('os', models.CharField(max_length=40, verbose_name='سیستم عامل')),
                ('os_version', models.CharField(max_length=20, verbose_name='نسخه سیستم عامل')),
                ('browser', models.CharField(max_length=40, verbose_name='مرورگر')),
                ('browser_version', models.CharField(max_length=20, verbose_name='نسخه مرورگر')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_log', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'لاگ',
                'verbose_name_plural': 'لاگ ها',
                'ordering': ['-created'],
            },
        ),
    ]
