# Generated by Django 4.2.4 on 2023-08-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_info_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.URLField(default='https://facebook.com'),
        ),
        migrations.AlterField(
            model_name='social',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AlterField(
            model_name='social',
            name='pinterest',
            field=models.URLField(default='https://www.pinterest.com/'),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.URLField(default='https://twitter.com'),
        ),
        migrations.AlterField(
            model_name='social',
            name='youtube',
            field=models.URLField(default='https://youtube.com/'),
        ),
    ]
