# Generated by Django 4.2.4 on 2023-08-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_info_phone_alter_social_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='about_image',
            field=models.ImageField(default=1, upload_to='main_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='main_logo',
            field=models.ImageField(default='', upload_to='main_images'),
            preserve_default=False,
        ),
    ]
