# Generated by Django 4.2.4 on 2023-08-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_info_about_image_info_main_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='website_logo',
            field=models.ImageField(default='', upload_to='main_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='website_title',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
