# Generated by Django 4.2.4 on 2023-08-19 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_info_website_logo_info_website_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=40)),
                ('client_ip', models.GenericIPAddressField()),
                ('device', models.CharField(max_length=40)),
                ('os', models.CharField(max_length=40)),
                ('os_version', models.CharField(max_length=20)),
                ('browser', models.CharField(max_length=40)),
                ('browser_version', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
